export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_COMPLETE_TASK = 'TOGGLE_COMPLETE_TASK';
export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_ALL_TASKS = 'DELETE_ALL_TASKS';
export const CHANGE_FILTER = 'CHANGE_FILTER';

